added api methods
Kechkin/Converter pull request #1
Opened 2021-06-16 05:27 UTC by Kechkin

2021-06-16 09:33 UTC, lobanart-mera reviewed
General comment, exclude **pyc** files from repo

2021-06-16 09:33 UTC, lobanart-mera commented on base/views.py
>          return HttpResponse('Unauthorized', status=401)
It should be Unauthenticated. Unauthorized is 403 code and it has a different meaning

2021-06-16 09:33 UTC, lobanart-mera commented on base/views.py
> +        return JsonResponse(context)
does your UI support the JSON response? You use the same function for UI and API request, I guess UI request expects the different format of response...

2021-06-16 09:33 UTC, lobanart-mera commented on base/views.py
> +    return HttpResponse("There's no value or currency")
This response is not understand for api request, if request comes from API it should be in JSON format and response also should be in JSON format.
If request comes from UI, it should be in different format, because you use the Django templates (I guess)?
Yeap, UI can also support the JSON, but it's not a your case, because your UI is not JS application.

2021-06-16 09:33 UTC, lobanart-mera commented on base/views.py
> +    return JsonResponse({"Response": "400"})
you should define the message for error response and it should explain the error, not just error code. The user should understand what happened. The status code is not a part of response body, status code is part of http protocol.

2021-06-16 09:33 UTC, lobanart-mera commented on base/views.py
> +    form = Search_data(data_json)
class name should be a CamelCase

2021-06-16 09:33 UTC, lobanart-mera commented on base/views.py
> +        return JsonResponse(ctx)
the same about response format like for search function

2021-06-17 07:08 UTC, lobanart-mera requested changes

2021-06-17 07:08 UTC, lobanart-mera commented on base/views.py
> +    return JsonResponse({"Error": "invalid data"})
you can put validation result from form validation instead of making general message

2021-06-17 07:08 UTC, lobanart-mera commented on base/views.py
> +            return JsonResponse({"Response": "200"})
Response code in body.

2021-06-17 07:08 UTC, lobanart-mera commented on base/views.py
> +    return HttpResponse("invalid data")
the same about Django templates and form validation

2021-06-24 18:43 UTC, artlo commented on base/views.py
> +                username, password = (base64.b64decode(user_data[1])).decode().split(":")
Очень не надежно использовать имя пользователя как токен, очень легко взломать. тогда как минимум пароль тоже должен быть провалидирован. Иначе все это не надежно

2021-06-30 16:51 UTC, merged